spring:
    aop:
      proxy-target-class: true
    thymeleaf: 
      cache: false  
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/spring_boot_example?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      initialSize: 5
      minIdle: 5
      maxWait: 60000
      maxActive: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
    redis: 
      database: 0
      host: 127.0.0.1  
      password: 
      port: 6379
      ssl: true
      timeout: 2000
      pool:
        maxIdle: 8
        minIdle: 0
        maxActive: 8
        maxWait: -1
server:
  port: 8081


logging:
  config: classpath:log4j2.xml
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.sheng.entity